### ISSUE TITLE
[IDEA] SprinkleExtension

### ISSUE THREAD

**Issue by saleh-aleid** [zaiste/sprinkle#11]
Don’t support single object\data object
so i suggest this code to add or if you have something else to handle it

```
extension SprinkleObject<T> on T {
  BehaviorSubject<T> get reactive => BehaviorSubject<T>.seeded(this);
}
```

example:

`var user = User().reactive;`

**Comment by zaiste** [comment]
@saleh-aleid Yes, absolutely. Feel free to issue a PR

**Comment by zaiste** [comment]
It's now added in `0.0.5`.
