### ISSUE TITLE
Remove Manager registration process from main.dart build method

### ISSUE THREAD

**Issue by z-tc** [zaiste/sprinkle#5]
It should be very convenient to use the architecture at the top level of the app - main.dart, to be able to control theming, localization, etc.

To be able to do that, we need to change the place where we are registering Managers.

**Comment by zaiste** [comment]
@z-tc I was thinking about the same topics recently. Could you elaborate your suggestion?

**Comment by z-tc** [comment]
@zaiste maybe we can discuss this topic on some discord/slack channel...?

**Comment by zaiste** [comment]
@z-tc I'd prefer to do it here, so the reasoning is archived and visible for others later on. Could you describe the problem with the current approach as you see it? It doesn't have to be long. 😉

**Comment by z-tc** [comment]
@zaiste use case will be - I want to work with localization in a sprinkle manner - when the user changes language in the app, I want to have that info directly in main.dart and affect the app language. here is my build() method from main.dart:
```
@override
  Widget build(BuildContext context) {
    return Provider(
      data: locator<Overseer>(),
      child: Observer<Locale>(
        stream: _localizationManager.outLocalization$,
        onSuccess: (context, data) {
          return MaterialApp(
            locale: data,
            supportedLocales: AppLocalizations.supportedLocales,
            localizationsDelegates: [
              AppLocalizations.delegate,
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate,
            ],
           ...
    );
 ```
I accomplished this by registering Overseer Managers directly in locator, and then resolved it in main.dart.
I wonder is that a good way performance-wise and sprinkle-wise? 😉

**Comment by zaiste** [comment]
@z-tc I've released a [new video](https://www.youtube.com/watch?v=itvtXypbwkw) that talks about something similar. Please, check it out and let me know if it solves your problem.

**Comment by z-tc** [comment]
@zaiste nice video, well done! yes, I needed something like that you explained there, and I solved it with locator, but this is a cool way also. I think we can close this issue...
